# File: srv/CheckCandidates.srv

string[] candidates_ids   # List of file paths to the images of candidate objects

---
bool match_found           # True if a good candidate was found
string best_candidate_id # The ID/Path of the best match
float32 max_score          # The actual score of the best match
yolo11_seg_interfaces/Point2D position      # Coordinates of the goal
